[build]
  # Remove '--prefix client' because Netlify is already inside the client folder
  command = "npm run build"
  
  # Set relative to the client folder (Vite = dist, CRA = build)
  publish = "dist"
  
  # Point back to the root 'server' folder for functions
  functions = "../server"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
